### ISSUE TITLE
Path to plugins/ directory is hard-coded

### ISSUE THREAD

**Issue by fouram** [codename-B/bReport#1]
The path to the plugins/ folder is hardcoded, but my server runs with -P command line options to move the plugins directory elsewhere. This means that a separate plugins/ directory is created in the wrong location (relative to my server JAR). That can be corrected by retrieving the proper path using Plugins.getDataFolder() to find the proper location.

**Comment by ProjectBarks** [comment]
I will update that for you

**Comment by ProjectBarks** [comment]
This has been fixed in a commit and will be added as soon bukkit approves my project.
