### ISSUE TITLE
Enhancement: Pitch and Yaw with report Locations

### ISSUE THREAD

**Issue by fouram** [codename-B/bReport#2]
Often times, it is nice to see where a user was looking when they filed the report, not just be teleported to the spot they where standing but facing north. Perhaps make it a configurable option to store pitch and yaw (or perhaps just yaw, and looking straight ahead?) and restore those on teleporting to the report site. Just a convenience thing, really :3

**Comment by ProjectBarks** [comment]
That Will be added with no problem

**Comment by ProjectBarks** [comment]
This feature has been added and thanks for the recommendation.
